language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI npm run build
true:
  branch: master
notifications:
  slack:
    secure: e5Vo06TLWH0mAoCxH9QlMmQHEi3iIIqRyPYaYeGokUszXfmavuyhmJjfeUflOcKVDQgf3KA+H9i3aFwx/9/H1aRCnyZm1bYQYLIkq1H5fVkK88QJ231FqMVPl8TOr13bh1Zd/tMWcKsxf1kSw63y06W2rwHwsBksT3NYh6VX6LSjO6V1+NN5P2qGdzPxuAavpFnC+DTIhvKx6zflrocZw5Ak5KZY9Zyn9J/Slza2z7UuLS7rIl9gHZNMh6cI9617ag63XOrzrqY/fGgRShJWjRZsHItVdewuk3eBBJzSoJCD0Op9MU8bJZsqZEUA53J4QuQ2TRwkMX7/rVkhb6jv3azzAu0qSOWY5W7k6+xrFXQ2cM1/buqpEOhBbwoIdyAeMmysYxPOzdv7ZaXHVNW2eQPuihHDEAPGPaDKWNipxb6D4l4zr+AIwW5H0PcS0sdQelDzQjrJJlczCTErPq6V7QmyiTGpAffXeRlyaOSzYBuKASEO1o1btJnXcoq2RaDmhAd/iJZP8cANcdvLC93+bMm18gjJQSzOFsZqc1JMT2nvxbdagqKorg89y4cUWjjHwsTCgYlPGQYt0Aij0p3mQjuCG7roqdJj1rie/jSzheMD0SQ4cyPC8xzzrWuK4GxfqeeFkEkHPBktPphca+vbwJYlA5OoFvtZYtY+ZlGW31A=
