dist: trusty
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- sonar-scanner
- unset CI npm run build
true:
  branch: master
notifications:
  slack:
    rooms:
      - sytw:ow2Sf6wUNpEMbn6dabaRRUNF#2019-e08
addons:
	sonarcloud:
		organization: "sytw2019"
		token:
		secure: "tx85+kv+tSudqGB1psM6iBdQRTC37veB8R6Bvo2xgSzxJnO4PYw1dT+ld2R2JAx88yYjVKdwvgMTljyBjPPVRNAkZvqa+0Di1LgaA27DsJmwc5Zvu4h4c/2dAP4T5x2EQEjIBa3yZ5DbDIvscjhXgKCqU0ikA6zOwd8OmnVE7aYw9AoRibVuP9OUt+ntihyj9VQDXENPH5FYifl9ORZzXRyQoc1NzdAypQm2jcqdOaLUTg0LmJcWw+d3abC8IJDvZgk7XYblmyJy2umGSqrNje9iZQAnd63e0O4T8s8kFBvlEeWo24DhjsaN1oEDsStJC0gRV8pOhDUn1YWod8ljljitlV5wCbwvJH7rY1eLh2t5MXgXGFWaXOZeE0pmULBA+BQ02kd3mMCh1ESvplldUqPMBv5II891TkxGVDOkaBp8sPC7+iAVQklUNUtwaimg3eW9PqeyXIwUbRkuek7fU+mpiOUT7FynBltcr5o8D2JebkvmEa+V7kVUNl6MXAFuA9SUnu0q6/sMxUNggA8ShLeXlnrq/EJ27UDrpxffqpTT5s55uwQN0XNElLuI48Z0i8k1bVofX7jhIshFgVVGo9YK+/EZmKksZXqX5K2++YGXU2lLYFxpIDUm8q7la9EC5AS+fvC2F9ui56zffmrvALFPeoAkRrg5Jg1TmRqgZMc="
