language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI npm run build
true:
  branch: master
notifications:
  slack:
    rooms:
      secure: L3S8IS09KKRjucFvdvZ0ARhm3Ccdnx74JUPWXk0yaXXCcEdMlCF3jYbjWbuq0xToJ/j6fiMdPsweB0rH5DtLADnTVL5H+ubPJVuek1JUxUkWYU9ZFzkgAnwGQyQZ/J5stbrgN57x+CQe2hxqEjlixQ6hEWNs9bnj5mrq20YvQxv0bjrTn1kugc2uh2Y4P2RgfBioqL0gvwEaQbGYbXEKKB3POi/yx03iNyrbLpXCcJZM/O2fEv/IcNj7ScOrS5Y6LFBvyOAnZiUxEXh6biIRWxLDmditw4jx/wC6LOmMA8WDctsbnk5pjUVAVe3kxHJ9CTE0eNVDvuMIqYH7eWeKi0L4ClB7HIXN9Rfo+ASUOV21qcQL53lHlKh9LxEsdl/uyr2BdbnRdaR2qtqXdcN+3Ig3lVmCgfjp3XlTioidgQFpz/TKh7OuineFbJ41P2R14gvPp4Vb4FDD/g83AMNZQ+iBzWPyDr8cysJ96rhFr8MJuQey60qy9gAflj5qE3pT3NjB+Cc7C4oAJ6lqqqKXjqxFj+Yng0cK6xeQuLI1FkficpAhln3iECBMzKiwR7q7Iy9Xrotfm6aNY39h0W9PXYGkj1vVrHRN9zR2GbgyNPFW8Ykrm6uEenCii2P31++xYHzxChPgRG/H40COtOIsbtolEniW+7Zghf171+wiP+o=
