language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI npm run build
true:
  branch: master
notifications:
  slack:
    rooms: sytw:BElmeEnhTSiVAJDcPdn51obH#2019-e08
