language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI npm run build
true:
  branch: master
notifications:
  slack:
    rooms:
      secure: IIJ7QcldI7W/+7+8FSBV2QVP8TNcIQirR7CbJGaoD6uuJMUXn09lpjWKuf1+eVmgA0+jNuLAtPbMP5v+UT1SChuDnv68WgRohoGnXvq54tMoqw7MJcN9LCc1TqVSlswv2C2Ijid0fXW7gsA6VB8xacb9PHi6VszwKr3nd6JoJU+/cT/Pwd2/89mBDw8fHD4z6u0XVe+ZXj67RqdL0y9p99E4x+kapj8fNGMVJBW33qGmw5h+VVUihSCoalcXwyQYvfu6c/OiXDcFFZIf8PZCWQEyljgY+5EPeiVxKw3ckG+Qih9MUbD9WMB2HE+1kw/VVR+CLloH630Hx6Bw0emjCZvjBgLDF+d0eOwaEnZjvDWGuFoH511u3DHaoM59RMVF8tsfAKD8DMeEMM1NdUFnI81jxRTOWVEMDeylqslvy4ibgPpI7+Mf9kxy0QlgcdQkCuwCCZfGHVf/G1wuREywO/6PH7bxyqeC/63VjnMGc8neyqavdXjmUMYj8pSBKIDm+ladlmhrAG7wOc8lvGHIjIXgEmdePBg9u4MK09En/OU5+/Hy2f3n6rilliofMrYzvpXz7W9A66THybv809jm8R5EuXy+4KzspC9LfA111V2QQ+9UvJj5mDFwgkwkcRZl1nSTmBlvIo9W+WKbBU0EHgjQ5asZtxQ38l1VbvikmWc=
