language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- unset CI npm run build
true:
  branch: master
notifications:
  slack:
    secure: HZsbC6mWT78FiNyX0K0+XLGuvsOZZfSRMwd2w74VRY7LfiDxGwy5ei6Vt0Y+244FiH7FYRMZEH4ggnmJ5qzhn48WzZp8TVPeOZplroh2z6HaSEeWks8TSKIagyd9nk8bCJ/p7YY5Ew7VbhUkoHgBIDAHwXvI/sK9KTMAahiSbSWgy8LGd7m0G3KKI/L3T3PJEPHEy9QPnS9onKWh1yGj5CsffD7YSH88mK3h6NhPbZVobfyVTZcf0sr7j7eSfGx9XH8zRaXzOEoMgj2TFmfUTdHVhGAXH14i901Y5mCb0V2kNebDnxzGElTynDKjhxXr+KJjMJ1gwGYe4pA5xSnQUxPNRHddLkSeSeHaHC+KTO9H9Np2tfkcgcbZ03v0FZ1CVgMblLcUWXST4hwXcqoqFN1egQpj+52Rmt1N81+whMC+y+R5RbvpvSmkgCELT+ipnF/bgYHNNgkoNZspDRmp/dQm/6z0cyyT89IyZYz93ALDa0LoBRuYDNU2x4Iz6OaQPrkwDrbHF8VMQF6v3du3upxTSO/NZfsDNqRY1gGhTJyQF6C11WMOHbildi5wuwQgYRJfxv/UFI8G716FE1DKTk5RbTSRwmD9f+K640DWoSrGXAtbyYM36l1AM0c+3RI2A4XOPHwkXqmgP2qX5J+bfRtQgVdlEG309vrpc5G4vXc=
